module.exports = [
    { title: "Wake up!",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [5, "zouro"],
        [7, "zouro"],
        [9, "zouro"],
        [13, "zouro"],
        [18, "zouro"],
        [19, "zouro"],
        [20, "zouro"],
        [21, "zouro"]
      ] },
    { title: "This is such a cold space",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [5, "zouro"],
        [7, "zouro"],
        [9, "zouro"],
        [13, "zouro"],
        [13, "zouro"],
        [16, "zouro"],
        [18, "zouro"],
        [20, "zouro"],
        [24, "zouro"],
        [24, "zouro"]
      ] },
    { title: "I should not rest",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [3, "zouro"],
        [4, "zouro"],
        [8, "zouro"],
        [8, "zouro"],
        [8, "zouro"],
        [10, "zouro"],
        [14, "zouro"],
        [14, "zouro"],
        [19, "zouro"],
        [19, "zouro"],
        [19, "zouro"],
        [19, "zouro"]
      ] },
    { title: "New friends?",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [8, "ouno"],
        [13, "zouro"],
        [13, "zouro"],
        [16, "zouro"],
        [18, "ouno"],
        [22, "zouro"],
        [22, "zouro"],
        [22, "zouro"],
        [26, "ouno"],
        [26, "ouno"]
      ] },
    { title: "Dehydrated lemon pie. Yummie!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [3, "zouro"],
        [7, "zouro"],
        [7, "trouo"],
        [8, "zouro"],
        [9, "trouo"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [15, "ouno"],
        [15, "ouno"],
      ] },
    { title: "There has been better holidays",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [2, "zouro"],
        [4, "zouro"],
        [4, "zouro"],
        [8, "zouro"],
        [8, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [26, "ouno"],
        [26, "ouno"],
      ] },
    { title: "Born to beeee wiiiillldddd!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [9, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "zouro"],
        [20, "ouno"],
        [26, "douo"],
      ] },
    { title: "What is that funky smell?!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [10, "douo"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [24, "douo"],
        [26, "douo"],
        [26, "douo"],
      ] },

  ];

